### PR TITLE
Update regex yaml

### PR DESCRIPTION
**Pull request by randyzwitch**

### CODE REVIEW

**Comment by randyzwitch** [comment]
Travis says tests fail, tests run just fine locally? I'm inclined to merge anyway, as the test files are provided from the main project, and I didn't modify the parsing code in any way.

```julia

julia> Pkg.test("UAParser")
INFO: Testing UAParser
INFO: UAParser tests passed

julia> using UAParser, YAML, Base.Test

julia> test_device = YAML.load(open(Pkg.dir("UAParser", "test", "data", "test_device.yaml")));

julia> for test_case in test_device["test_cases"]
         @test test_case["family"] == parsedevice(test_case["user_agent_string"]).family
       end

julia> test_os = YAML.load(open(Pkg.dir("UAParser", "test", "data", "test_user_agent_parser_os.yaml")));

julia> for value in test_os["test_cases"]
         @test Dict{Any, Any}("major" => value["major"],
             "minor" => value["minor"],
             "patch" => value["patch"],
             "patch_minor" => value["patch_minor"],
             "family" => value["family"]) ==
             Dict{Any, Any}("major" => parseos(value["user_agent_string"]).major,
              "minor" => parseos(value["user_agent_string"]).minor,
              "patch" => parseos(value["user_agent_string"]).patch,
              "patch_minor" => parseos(value["user_agent_string"]).patch_minor,
              "family" => parseos(value["user_agent_string"]).family)
       end

julia> test_os_2 = YAML.load(open(Pkg.dir("UAParser", "test", "data", "additional_os_tests.yaml")));

julia> for value in test_os_2["test_cases"]
       @test Dict{Any, Any}("major" => value["major"], "minor" => value["minor"], "patch" => value["patch"], "patch_minor" => value["patch_minor"], "family" => value["family"]) ==
            Dict{Any, Any}("major" => parseos(value["user_agent_string"]).major,
              "minor" => parseos(value["user_agent_string"]).minor,
              "patch" => parseos(value["user_agent_string"]).patch,
              "patch_minor" => parseos(value["user_agent_string"]).patch_minor,
              "family" => parseos(value["user_agent_string"]).family)
       end

julia> test_ua = YAML.load(open(Pkg.dir("UAParser", "test", "data", "test_user_agent_parser.yaml")));

julia> for value in test_ua["test_cases"]
       @test Dict{Any, Any}("major" => value["major"], "minor" => value["minor"], "patch" => value["patch"], "family" => value["family"]) ==
           Dict{Any, Any}("major" => parseuseragent(value["user_agent_string"]).major,
            "minor" => parseuseragent(value["user_agent_string"]).minor,
            "patch" => parseuseragent(value["user_agent_string"]).patch,
            "family" => parseuseragent(value["user_agent_string"]).family)
       end

julia> test_ua_2 = YAML.load(open(Pkg.dir("UAParser", "test", "data", "firefox_user_agent_strings.yaml")));

julia> for value in test_ua_2["test_cases"]
       @test Dict{Any, Any}("major" => value["major"], "minor" => value["minor"], "patch" => value["patch"], "family" => value["family"]) ==
            Dict{Any, Any}("major" => parseuseragent(value["user_agent_string"]).major,
            "minor" => parseuseragent(value["user_agent_string"]).minor,
            "patch" => parseuseragent(value["user_agent_string"]).patch,
            "family" => parseuseragent(value["user_agent_string"]).family)

       end

```

**Comment by randyzwitch** [comment]
Merging anyway; as the developer, I'm asserting that it is correct. All the tests pass on OSX on my machine using Version 0.4.3-pre+3 (2015-12-07 13:47 UTC).

**Comment by IainNZ** [comment]
Tests now fail on the PackageEvaluator machine as well

**Comment by IainNZ** [comment]
http://pkg.julialang.org/logs/UAParser_0.4.log

**Comment by randyzwitch** [comment]
Do you have any thoughts on what might be causing this? I don't get the failure on OSX, but separate CI platforms do get the error.

**Comment by IainNZ** [comment]
Some sort of difference in the underlying regex library?

**Pull request merged**
